### ISSUE TITLE
Cannot build project after add this plugin

### ISSUE THREAD

**Issue by johnwatsondev** [cjstehno/dependency-checker#4]
### ENV
Android Studio 2.3
Build #AI-162.3764568, built on February 24, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

gradle-wrapper.properties:

```
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
```

Root Project build.gradle:

```
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:2.4.0-alpha1'
  }
}
```

app module build.gradle:

```
plugins {
  id "com.stehno.gradle.dependency-checker" version "0.2.1"
}
```

### LOG

Error:(10, 0) Cannot set the value of read-only property 'name' for task ':app:checkDependencies' of type com.stehno.gradle.depchecker.CheckDependenciesTask.

**Comment by cjstehno** [comment]
This should be resolved in the 0.2.2 release (dropping shortly).
